"""add per-project full access grants

Ngoai 3 role co dinh (user/admin/super_admin), Super Admin co the gan
them "full quyen" (Confirm/Reject + Run) cho 1 user cu the tren 1 Group
(project) cu the + toan bo Project (application) con ben trong, doc lap
voi role hien tai cua user do. Khong doi enum role, chi them bang grant.

Revision ID: 3642a0ac1cf9
Revises: 5c8d7c3c9e70
Create Date: 2026-07-27 02:51:04.559846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3642a0ac1cf9'
down_revision: Union[str, Sequence[str], None] = '5c8d7c3c9e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_admin_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_admin_access')
    # ### end Alembic commands ###
